development:
  s3:
    access_key_id: 'xxxxxx'
    secret_access_key: 'xxxxxx'
    bucket: 's3.bucket.name'

test:
  s3:
    access_key_id: 'xxxxxx'
    secret_access_key: 'xxxxxx'
    bucket: 's3.bucket.name'

production:
  s3:
    access_key_id: 'xxxxxx'
    secret_access_key: 'xxxxxx'
    bucket: 's3.bucket.name'
