# you must keep all keys on one level so that the heroku:config rake task can turn them into environment variables

development:
  S3_KEY: xxxxxx
  S3_SECRET: xxxxxx
  S3_BUCKET: s3.bucket.name
  DEV_PAYMENT_LOGIN: xxxxxx
  DEV_PAYMENT_PASSWORD: xxxxxx
  DEV_PAYMENT_SIGNATURE: xxxxxx
  PROD_PAYMENT_LOGIN: xxxxxx
  PROD_PAYMENT_PASSWORD: xxxxxx
  PROD_PAYMENT_SIGNATURE: xxxxxx
  USER_NAME: xxxxxx
  USER_PW: xxxxxx

test:
  S3_KEY: xxxxxx
  S3_SECRET: xxxxxx
  S3_BUCKET: s3.bucket.name
  DEV_PAYMENT_LOGIN: xxxxxx
  DEV_PAYMENT_PASSWORD: xxxxxx
  DEV_PAYMENT_SIGNATURE: xxxxxx
  PROD_PAYMENT_LOGIN: xxxxxx
  PROD_PAYMENT_PASSWORD: xxxxxx
  PROD_PAYMENT_SIGNATURE: xxxxxx
  USER_NAME: xxxxxx
  USER_PW: xxxxxx

production:
  S3_KEY: xxxxxx
  S3_SECRET: xxxxxx
  S3_BUCKET: s3.bucket.name
  DEV_PAYMENT_LOGIN: xxxxxx
  DEV_PAYMENT_PASSWORD: xxxxxx
  DEV_PAYMENT_SIGNATURE: xxxxxx
  PROD_PAYMENT_LOGIN: xxxxxx
  PROD_PAYMENT_PASSWORD: xxxxxx
  PROD_PAYMENT_SIGNATURE: xxxxxx
  USER_NAME: xxxxxx
  USER_PW: xxxxxx
